import type { NextPage } from 'next'
import Head from 'next/head'
import Main from '../src'
import Footer from '../src/components/Footer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Main />
            </main>

            <footer className={styles.footer}>
                <Footer />
            </footer>
        </div>
    )
}

export default Home
