import type { NextPage } from 'next'
import Head from 'next/head'
import Table from '../src/index'
import Footer from '../src/components/Footer'
import styles from '../styles/Home.module.css'
import clsx from 'clsx'

const Home: NextPage = () => {
    return (
        <div className={clsx('bg-gray-100')}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="min-h-screen max-w-xl">
                <Table />
            </main>

            <footer className={styles.footer}>
                <Footer />
            </footer>
        </div>
    )
}

export default Home
